version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: broadband-stats-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: broadbanddb
    command: [ "mongod", "--logpath", "/var/log/mongodb/mongod.log", "--quiet", "--logappend" ]
    ports:
      - "27017:27017"
    volumes:
      - /mnt/HC_Volume_104081075/affMktProducts:/data/db
    networks:
      - broadband-stats-network

volumes:
  mongodb_data:
    driver: local

networks:
  broadband-stats-network:
    driver: bridge
